### ISSUE TITLE
Negeer transacties met onbekende stations

### ISSUE THREAD

**Issue by joostrijneveld** [mrngm/besparing#1]
Mijn transactiegeschiedenis bevat de volgende twee entries:
```
"08-01-2017";"";"Schiphol Airport";"20:21";"Nijmegen";"11,80";"Check-uit";"";"Dal Voordeel (2e klas)";""
"09-01-2017";"";"Nijmegen, Centraal Station";"08:48";"Nijmegen, Station Heyendaal";"1,22";"Check-uit";"";"";""
```

De eerste gaat prima; Nijmegen is immers een NS-station. De tweede levert echter een `Could not find station`-error op, omdat Arriva besloten heeft dat ditzelfde station `Nijmegen, Centraal Station` heet. Dit speelt natuurlijk voor alle stations die NS onder een andere naam kent, of waar NS überhaupt niet rijdt.

Misschien is 't wenselijk om die exception in `besparing.py` af te handelen.

**Comment by mrngm** [comment]
Wat zou je suggeren? Iets als een `localOverrides.py` met een dictionary van _alternative names_ naar stationscodes? Misschien een lijstje met _closest matches_ laten zien en een keuze opgeven?

Edit: ik kan ook even naar de issue-titel kijken, maar dit lijkt me ergens onwenselijk. Gewoon negeren is natuurlijk wel een easy-fix.

**Comment by joostrijneveld** [comment]
Ah, ik was in de (verkeerde, zo blijkt) veronderstelling dat abbonementen van NS gewoon niet zouden werken op trajecten van andere vervoerders - dit soort transacties negeren leek me dan ook een correcte aanpak; ze zouden immers geen invloed hebben op de eventuele besparing / meerprijs van een abonnement.

Aliassen voor dit soort gevallen lossen 't helaas niet helemaal op, want het gaat juist om stations waarvoor tariefinformatie niet beschikbaar is in de lijsten van NS. Datzelfde gebeurt met 'closest matches'; dat zijn NS-stations, terwijl dit probleem juist ontstaat wanneer een andere vervoerder in 't spel is.

De afstandenmatrix lijkt gelukkig dekkend voor alle stations. Helaas kon ik bij (bijvoorbeeld) Arriva niet meteen een tarievenoverzicht vinden.. Op basis van m'n transactiegeschiedenis en een configuratie (dwz 'welk abonnement had ik toen') is een ritprijs af te leiden, maar ik kan me voorstellen dat de bijbehorende logica nogal ingewikkeld kan worden rondom de randjes (om Arriva's variabele daluren per regio nog maar even buiten beschouwing te laten..). Een verbetering zou al zijn om dit soort transacties los te tonen (al dan niet gesommeerd per traject), en aan te geven dat dat wat handmatig inzicht vereist.

**Comment by mrngm** [comment]
> Een verbetering zou al zijn om dit soort transacties los te tonen (al dan niet gesommeerd per traject), en aan te geven dat dat wat handmatig inzicht vereist.

Dat lijkt me inderdaad een betere optie. Er zijn wel afstandenmatrices voor andere vervoerders (zie `csv/README.md`), maar dat levert nog niet de tarieven op daarvoor. Mijn usecase is vrij specifiek: ik reis alleen via NS (vooralsnog).

Mocht je een tarieventabel tegenkomen, graag, maar ik vermoed dat bepalen of je via Arriva, NS of anders hebt gereisd (aan de hand van het transactieoverzicht), wat mij betreft, buiten de scope van deze tool gaat zijn.

Een (voor jou nuttige) fix zou kunnen zijn de _algehele_ afstandentabel in te laden. Je hebt dan wel de tariefafstanden en kan een _indicatie_ krijgen van de kosten. Zie bijv. het verschil (i.e. history van) [deze gist](https://gist.github.com/mrngm/0dcda8e4e96f39cd16a774bc66839ace/revisions). De eerste is met 'alle afstanden', de tweede met 'alleen NS'. Het verschil is al vrij snel duidelijk. In de repo staat die onder `csv/afstandenmatrix-2017-01.csv`, en [hier](https://github.com/mrngm/besparing/blob/master/tarieven.py#L62) verander je bron voor de tariefafstanden. Enige is dan dat je handmatig (in je transactieoverzicht) de stationsnamen moet veranderen.

**Comment by joostrijneveld** [comment]
Ah, je hebt gelijk - ik dacht dat 't fout zou gaan wanneer ik de hele afstandentabel in zou laden zonder bijbehorende tarieven, maar gewoon NS-tarieven hanteren is dan natuurlijk een prima alternatief.

Arriva is voor mij persoonlijk ook niet echt relevant; als ik drie keer per jaar in een niet-NS-trein zit is het veel. Ik kwam 't meer bij toeval tegen, omdat een van die drie keren toevallig in afgelopen januari was.

**Comment by mrngm** [comment]
Ik heb in 38b9ec7 het gefixt; wil je het nog testen?

**Comment by joostrijneveld** [comment]
Ziet er goed uit! Nu valt me op dat voor busritjes hetzelfde gebeurt, en dat is helemaal een rabbithole.
`>>> Warning: skipping transaction between 'Utrecht, Tweede Westerparklaan' and 'Utrecht, CS Jaarbeurszijde (Perron D1)'.`

**Comment by mrngm** [comment]
Goeie; wederom niet echt een usecase aan mijn kant, maar dan zie je in ieder geval wat er gebeurt. Fun fact, in de stationslijst zit ook "Utrecht Uithof (NS-bus)"

Anyway, lijkt me gefixt, ik ga 'm mergen. Thanks voor de bugreport.
